border          = "#bfbdb6"
border_selected = "#e6b450"
border_dead     = "#f07178"
status_running  = "#aad94c"
status_sleeping = "#e6b450"
status_dead     = "#f07178"
status_unknown  = "#565b66"
sparkline       = "#59c2ff"
sparkline_dead  = "#565b66"
