border          = "white"
border_selected = "cyan"
border_dead     = "red"
status_running  = "green"
status_sleeping = "yellow"
status_dead     = "red"
status_unknown  = "darkgray"
sparkline       = "cyan"
sparkline_dead  = "darkgray"
