border          = "#ebdbb2"
border_selected = "#fabd2f"
border_dead     = "#fb4934"
status_running  = "#b8bb26"
status_sleeping = "#fabd2f"
status_dead     = "#fb4934"
status_unknown  = "#928374"
sparkline       = "#83a598"
sparkline_dead  = "#665c54"
