border          = "#c6c6c6"
border_selected = "#2eb398"
border_dead     = "#e05252"
status_running  = "#2eb398"
status_sleeping = "#e5c07b"
status_dead     = "#e05252"
status_unknown  = "#7a7a7a"
sparkline       = "#2eb398"
sparkline_dead  = "#5c5c5c"
